version: '3.8'

services:
  app:
    build: .
    container_name: whatsapp-fastify-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./whatsapp-session:/app/whatsapp-session
    env_file:
      - .env
    restart: unless-stopped